# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  inputs:
    workingDirectory: '$(System.DefaultWorkingDirectory)/setup/'
    filePath: '$(System.DefaultWorkingDirectory)/setup/pipeline_setup.sh'
    env:
      ARM_CLIENT_ID: $(CLIENT_ID)
      ARM_CLIENT_SECRET: $(CLIENT_SECRET)
      ARM_SUBSCRIPTION_ID: $(SUBSCRIPTION_ID)
      ARM_TENANT_ID: $(TENANT_ID)
      RESOURCE_GROUP_NAME: $(RESOURCE_GROUP_NAME)
      RESOURCE_GROUP_LOCATION: $(LOCATION)
      DATA_COLLECTOR_TOKEN: $(DC_TOKEN)
      CHEF_AUTOMATE_LICENSE: $(CHEF_AUTOMATE_LICENSE)
      CHEF_AUTOMATE_ADMIN_PASSWORD: $(CHEF_AUTOMATE_ADMIN_PASSWORD)
